name: Housekeeping Checks
on: [pull_request]
jobs:
  backend_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
            java-version: '11'
            distribution: 'adopt'
      - run: ./.github/workflows/housekeeping_scripts/backend_lint.sh
  frontend_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: ./.github/workflows/housekeeping_scripts/frontend_lint.sh